tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.5/types.yaml
  - http://www.getcloudify.org/spec/utilities-plugin/1.15.3/plugin.yaml

node_templates:

  deployment_proxy:
    type: cloudify.nodes.DeploymentProxy
    properties:
      resource_config:
        blueprint:
          external_resource: true
          id: deployment_proxy
        deployment:
          external_resource: true
          id: deployment_proxy
          outputs:
            key: deployment_proxy_output
